#Programa para juntar todos los xls en una tabla y exportar un RDATA
library("readxl")

alta_Verapaz <- read_excel("ALTA VERAPAZ.xlsx")
baja_Verapaz <- read_excel("BAJA VERAPAZ.xlsx")
chimaltenango <- read_excel("CHIMALTENANGO.xlsx")
chiquimula <- read_excel("CHIQUIMULA.xlsx")
ciudad <- read_excel("datos de ciudad capital.xlsx")
guatemala <- read_excel("datos de guatemala.xlsx")
el_progreso <- read_excel("EL PROGRESO.xlsx")
escuintla <- read_excel("ESCUINTLA.xlsx")
huehue <- read_excel("HUEHUETENANGO.xlsx")
izabal <- read_excel("IZABAL.xlsx")
jalapa <- read_excel("JALAPA.xlsx")
peten <- read_excel("PETEN.xlsx")
quetzaltenango <- read_excel("QUETZALTENANGO.xlsx")
quiche <- read_excel("QUICHE.xlsx")
retalhuleu <- read_excel("RETALHULEU.xlsx")
sacatepequez <- read_excel("SACATEPEQUEZ.xlsx")
san_marcos <- read_excel("SAN MARCOS.xlsx")
santa_rosa <- read_excel("SANTA ROSA.xlsx")
solola <- read_excel("SOLOLA.xlsx")
suchi <- read_excel("SUCHITEPEQUEZ.xlsx")
toto <- read_excel("TOTONICAPAN.xlsx")
zacapa <- read_excel("ZACAPA.xlsx")

republica_guatemala <- rbind(alta_Verapaz, baja_Verapaz, chimaltenango, chiquimula, ciudad, guatemala, el_progreso, escuintla, huehue, izabal, jalapa, peten, quetzaltenango, quiche, retalhuleu, sacatepequez, san_marcos, santa_rosa, solola, suchi, toto, zacapa)

save(republica_guatemala, file = "republica_guatemala.RData")
